### ISSUE TITLE
Support Directory Arg

### ISSUE THREAD

**Issue by ashtonian** [kesonan/goimportx#1]
Nice project. I'd like to use it on my whole project. 

Right now here is workaround.

```sh
find . -name '*.go' ! -path './vendor/*' -exec goimportx --write --file {} \;
```

Also it panicked against my vendor folder. 
```
panic: invalid line number 0 (should be >= 1)

goroutine 1 [running]:
go/token.(*File).LineStart(0x1400010dbc0?, 0x3?)
	/opt/homebrew/Cellar/go/1.20.6/libexec/src/go/token/position.go:212 +0x1cc
go/ast.sortSpecs(0x1?, 0x1400019f8b8, {0x1400010dc80, 0x3, 0x4})
	/opt/homebrew/Cellar/go/1.20.6/libexec/src/go/ast/import.go:118 +0x18c
go/ast.SortImports(0x1?, 0x1400019f8b8)
	/opt/homebrew/Cellar/go/1.20.6/libexec/src/go/ast/import.go:39 +0x350
github.com/anqiansong/goimportx/pkg/importx.(*ImportSorter).Sort(0x1400013a1b0?, {0x14000148c00, 0x4, 0x1400019faf0?})
	/Users/ashtonian/go/pkg/mod/github.com/anqiansong/goimportx@v0.0.2/pkg/importx/sort.go:25 +0xd4
github.com/anqiansong/goimportx/pkg/importx.Sort({0x16f407139?, 0x0?}, {0x0?, 0x0?})
	/Users/ashtonian/go/pkg/mod/github.com/anqiansong/goimportx@v0.0.2/pkg/importx/importx.go:163 +0x49c
github.com/anqiansong/goimportx/cmd.glob..func1(0x100e9d0e0?, {0x100c37281?, 0x3?, 0x3?})
	/Users/ashtonian/go/pkg/mod/github.com/anqiansong/goimportx@v0.0.2/cmd/cmd.go:21 +0x4c
github.com/spf13/cobra.(*Command).execute(0x100e9d0e0, {0x1400010c050, 0x3, 0x3})
	/Users/ashtonian/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x100e9d0e0)
	/Users/ashtonian/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/ashtonian/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/anqiansong/goimportx/cmd.Execute()
	/Users/ashtonian/go/pkg/mod/github.com/anqiansong/goimportx@v0.0.2/cmd/cmd.go:50 +0xb4
main.main()
	/Users/ashtonian/go/pkg/mod/github.com/anqiansong/goimportx@v0.0.2/main.go:6 +0x1c
```

**Comment by kesonan** [comment]
see https://github.com/kesonan/goimportx/pull/2
